{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "envpilot-control-plane.fullname" . }}-env
  labels:
    {{- include "envpilot-control-plane.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.postgres.enabled (not .Values.postgres.auth.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "envpilot-control-plane.postgresName" . }}
  labels:
    {{- include "envpilot-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  {{ .Values.postgres.auth.passwordKey }}: {{ .Values.postgres.auth.password | quote }}
{{- end }}
