apiVersion: v1
kind: Service
metadata:
  name: {{ include "envpilot-control-plane.fullname" . }}
  labels:
    {{- include "envpilot-control-plane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "envpilot-control-plane.selectorLabels" . | nindent 4 }}
