FROM golang:1.25 AS build
ARG TARGETOS
ARG TARGETARCH
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY cmd ./cmd
RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH:-amd64} go build -trimpath -ldflags='-s -w' -o /out/platform-reconciler ./cmd/platform-reconciler

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/platform-reconciler /platform-reconciler
USER nonroot:nonroot
ENTRYPOINT ["/platform-reconciler"]
