{{- $podAnnotations := mergeOverwrite (deepCopy (default (dict) .Values.podAnnotations)) (include "envplane-e2e-workload.imageMetadata" . | fromYaml) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "envplane-e2e-workload.fullname" . }}
  labels:
    {{- include "envplane-e2e-workload.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "envplane-e2e-workload.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "envplane-e2e-workload.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        {{- toYaml $podAnnotations | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: e2e-workload
          image: {{ include "envplane-e2e-workload.image" . | quote }}
          imagePullPolicy: {{ include "envplane-e2e-workload.imagePullPolicy" . }}
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "envplane-e2e-workload.fullname" . }}
  labels:
    {{- include "envplane-e2e-workload.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "envplane-e2e-workload.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
