{{- if and .Values.controlPlane.authPersistence.enabled .Values.controlPlane.authPersistence.createClaim (not .Values.controlPlane.authPersistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default (printf "%s-auth" (include "envplane-runner.fullname" .)) .Values.controlPlane.authPersistence.claimName }}
  labels:
    {{- include "envplane-runner.labels" . | nindent 4 }}
    {{- include "envplane-runner.managedRemoteMetadata" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.controlPlane.authPersistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.controlPlane.authPersistence.size | quote }}
  {{- if .Values.controlPlane.authPersistence.storageClassName }}
  storageClassName: {{ .Values.controlPlane.authPersistence.storageClassName | quote }}
  {{- end }}
{{- end }}
