{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "envplane-runner.fullname" . }}
  labels:
    {{- include "envplane-runner.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "envplane-runner.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: health
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval | quote }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout | quote }}
{{- end }}
