apiVersion: v2
name: envpilot
description: EnvPilot same-cluster umbrella chart.
type: application
version: 0.3.35
appVersion: "0.3.35"
dependencies:
  - name: envpilot-control-plane
    version: 0.3.16
    repository: file://../envpilot-control-plane
    condition: controlPlane.enabled
  - name: envpilot-frontend
    version: 0.2.1
    repository: file://../envpilot-frontend
    condition: frontend.enabled
  - name: envpilot-agent
    version: 0.2.5
    repository: file://../envpilot-agent
    condition: agent.enabled
  - name: envpilot-runner
    version: 0.4.0
    repository: file://../envpilot-runner
    condition: runner.enabled
