apiVersion: v2
name: envpilot
description: EnvPlane same-cluster umbrella chart.
type: application
version: 0.3.38
appVersion: "0.3.38"
dependencies:
  - name: envpilot-control-plane
    version: 0.3.24
    repository: file://../envpilot-control-plane
    condition: controlPlane.enabled
  - name: envpilot-frontend
    version: 0.2.1
    repository: file://../envpilot-frontend
    condition: frontend.enabled
  - name: envpilot-agent
    version: 0.2.6
    repository: file://../envpilot-agent
    condition: agent.enabled
  - name: envpilot-runner
    version: 0.4.1
    repository: file://../envpilot-runner
    condition: runner.enabled
  - name: envpilot-webhook
    version: 0.1.0
    repository: file://../envpilot-webhook
    condition: webhook.enabled
