#!/usr/bin/env bash
set -euo pipefail

# Diagnose an envplane zero-values installation without reading Secret objects
# or values. The optional output contains only a StorageClass name.
chart="oci://ghcr.io/envplane/envplane"
version=""
namespace="envplane"
context=""
output="-"

usage() {
  cat <<'EOF'
Usage: scripts/envplane-install-preflight.sh --version X.Y.Z [--namespace NAME]
       [--kube-context CONTEXT] [--chart OCI_REF] [--output FILE|-]

Checks anonymous OCI access, Kubernetes API reachability, the default
StorageClass, and the Helm caller's required RBAC. It never reads, prints, or
creates credentials or Secret data. On success it writes a safe StorageClass
override; use it only when an explicit class is desired.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version) version="${2:-}"; shift 2 ;;
    --namespace) namespace="${2:-}"; shift 2 ;;
    --kube-context) context="${2:-}"; shift 2 ;;
    --chart) chart="${2:-}"; shift 2 ;;
    --output) output="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

[[ "$version" =~ ^[0-9]+.[0-9]+.[0-9]+$ ]] || {
  echo "--version must be a published immutable SemVer X.Y.Z; latest is not supported" >&2
  exit 2
}
[[ "$namespace" =~ ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$ ]] || {
  echo "--namespace must be a Kubernetes DNS label" >&2
  exit 2
}
[[ "$output" == "-" || -n "$output" ]] || { echo "--output must be FILE or -" >&2; exit 2; }

kubectl_args=()
[[ -n "$context" ]] && kubectl_args+=(--context "$context")

kubectl "${kubectl_args[@]}" version --request-timeout=10s >/dev/null || {
  echo "Kubernetes API check failed. Verify the selected kube context and network access." >&2
  exit 1
}

required_namespace_verbs=(
  "create namespaces"
  "create deployments.apps"
  "create statefulsets.apps"
  "create services"
  "create secrets"
  "create persistentvolumeclaims"
  "create roles.rbac.authorization.k8s.io"
  "create rolebindings.rbac.authorization.k8s.io"
)
required_cluster_verbs=(
  "create clusterroles.rbac.authorization.k8s.io"
  "create clusterrolebindings.rbac.authorization.k8s.io"
  "get storageclasses.storage.k8s.io"
)
rbac_failed=false
for permission in "${required_namespace_verbs[@]}"; do
  if ! kubectl "${kubectl_args[@]}" auth can-i "${permission%% *}" "${permission#* }" --namespace "$namespace" | grep -qx yes; then
    echo "RBAC check failed: helm caller needs '${permission%% *} ${permission#*}' in namespace $namespace." >&2
    rbac_failed=true
  fi
done
for permission in "${required_cluster_verbs[@]}"; do
  if ! kubectl "${kubectl_args[@]}" auth can-i "${permission%% *}" "${permission#*}" | grep -qx yes; then
    echo "RBAC check failed: helm caller needs cluster-scoped '${permission%% *} ${permission#*}'." >&2
    rbac_failed=true
  fi
done
if [[ "$rbac_failed" == true ]]; then
  echo "Fix the Helm caller RBAC, then rerun this diagnostic. No resources were created." >&2
  exit 1
fi

storage_class="$(kubectl "${kubectl_args[@]}" get storageclass -o jsonpath='{range .items[?(@.metadata.annotations.storageclass\.kubernetes\.io/is-default-class=="true")]}{.metadata.name}{"\n"}{end}' | head -n1)"
if [[ -z "$storage_class" ]]; then
  echo "Storage check failed: no default StorageClass is configured. Ask the platform owner to set one, or rerun with an explicit supported StorageClass in an operator values file." >&2
  exit 1
fi

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
if ! helm pull "$chart" --version "$version" --destination "$tmp" >/dev/null 2>&1; then
  echo "Network check failed: anonymous Helm pull of $chart:$version did not succeed. Check outbound registry access and the published version; do not add registry credentials for public envplane artifacts." >&2
  exit 1
fi

override=$(cat <<EOF
# Generated by envplane-install-preflight.sh; contains no credentials.
envplane-control-plane:
  persistence:
    storageClassName: $storage_class
  postgres:
    persistence:
      storageClassName: $storage_class
  redis:
    persistence:
      storageClassName: $storage_class
EOF
)

if [[ "$output" == "-" ]]; then
  printf '%s\n' "$override"
else
  umask 077
  printf '%s\n' "$override" >"$output"
  echo "preflight passed; safe values override written to $output" >&2
fi
