#!/usr/bin/env bash
# Render the target-cluster RBAC profile consumed by envplane's Remote Cluster
# Reconciler. The result contains no credentials and can be reviewed before it
# is applied. Dynamic project namespaces receive workload access only through
# server-owned RoleBindings after ownership verification.
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: render-remote-cluster-rbac-profile.sh --cluster-id ID [options]

Options:
  --runtime-namespace NAME   Namespace for the envplane target runtimes (default: envplane-system)
  --managed-namespace NAME   Existing namespace for read-only workload discovery; repeatable
  --flux-namespace NAME      Existing namespace that also permits read-only Flux status; repeatable
  --help                     Show this help
EOF
}

cluster_id=""
runtime_namespace="envplane-system"
managed_namespaces=()
flux_namespaces=()

require_option_value() {
  local option="$1"
  if [[ $# -lt 2 || -z "${2:-}" || "${2:0:2}" == "--" ]]; then
    echo "$option requires a non-empty value" >&2
    usage >&2
    exit 2
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --cluster-id) require_option_value "$@"; cluster_id="$2"; shift 2 ;;
    --runtime-namespace) require_option_value "$@"; runtime_namespace="$2"; shift 2 ;;
    --managed-namespace) require_option_value "$@"; managed_namespaces+=("$2"); shift 2 ;;
    --flux-namespace) require_option_value "$@"; flux_namespaces+=("$2"); shift 2 ;;
    --help) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

dns_label='^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
for value in "$cluster_id" "$runtime_namespace"; do
  if [[ ! "$value" =~ $dns_label ]] || [[ ${#value} -gt 63 ]]; then
    echo "cluster ID and namespace names must be Kubernetes DNS labels up to 63 characters" >&2
    exit 2
  fi
done
service_account="envplane-remote-cluster-$cluster_id"
for namespace in "${flux_namespaces[@]}"; do
  if [[ ! "$namespace" =~ $dns_label ]] || [[ ${#namespace} -gt 63 ]]; then
    echo "Flux namespace names must be Kubernetes DNS labels up to 63 characters" >&2
    exit 2
  fi
done

prefix="envplane-remote-cluster-$cluster_id"
installer_principal="system:serviceaccount:$runtime_namespace:$service_account"
capability_role="$prefix-cluster-capability-reader"
inventory_role="$prefix-namespace-inventory-reader"
metadata_role="$prefix-namespace-metadata-reader"
all_namespaces=("$runtime_namespace")
unique_managed_namespaces=()
append_unique_managed_namespace() {
  local candidate="$1"
  local existing
  for existing in "${unique_managed_namespaces[@]}"; do
    if [[ "$existing" == "$candidate" ]]; then
      return 0
    fi
  done
  unique_managed_namespaces+=("$candidate")
}
append_unique_namespace() {
  local candidate="$1"
  local existing
  for existing in "${all_namespaces[@]}"; do
    if [[ "$existing" == "$candidate" ]]; then
      return 0
    fi
  done
  all_namespaces+=("$candidate")
}
for namespace in "${managed_namespaces[@]}"; do
  if [[ ! "$namespace" =~ $dns_label ]] || [[ ${#namespace} -gt 63 ]]; then
    echo "managed namespace names must be Kubernetes DNS labels up to 63 characters" >&2
    exit 2
  fi
  append_unique_managed_namespace "$namespace"
  append_unique_namespace "$namespace"
done
managed_namespaces=("${unique_managed_namespaces[@]}")

append_unique_flux_namespace() {
  local candidate="$1"
  local existing
  for existing in "${validated_flux_namespaces[@]}"; do
    if [[ "$existing" == "$candidate" ]]; then
      return 0
    fi
  done
  validated_flux_namespaces+=("$candidate")
}
validated_flux_namespaces=()
for namespace in "${flux_namespaces[@]}"; do
  append_unique_flux_namespace "$namespace"
done

cat <<EOF
# Generated by scripts/render-remote-cluster-rbac-profile.sh.
# Review this file before applying it. It intentionally contains no token,
# kubeconfig or other credential material.
apiVersion: v1
kind: Namespace
metadata:
  name: $runtime_namespace
  labels:
    app.kubernetes.io/part-of: envplane
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: $service_account
  namespace: $runtime_namespace
  labels:
    app.kubernetes.io/part-of: envplane
    envplane.io/owner: local-platform
    envplane.io/remote-cluster-id: $cluster_id
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: $prefix-installer
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "create", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles"]
    resourceNames:
      - $prefix-cluster-capability-reader
      - $prefix-namespace-inventory-reader
      - $prefix-namespace-metadata-reader
      - $prefix-rbac-manager
      - $prefix-discovery-parent
      - $prefix-feature-env-writer-parent
    verbs: ["bind"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles"]
    resourceNames:
      - $prefix-namespace-metadata-reader
    verbs: ["get", "update", "patch"]
  # Kubernetes RBAC cannot constrain create by resource name. The companion
  # ValidatingAdmissionPolicy below therefore permits these verbs only for a
  # Helm-owned Runner namespace-reader with the exact bounded rule shape.
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles"]
    verbs: ["create", "get", "update", "patch", "delete"]
  # The bind verb is evaluated by Kubernetes independently of admission. The
  # admission policy below constrains every corresponding ClusterRoleBinding
  # to a Helm-owned Runner namespace-reader with one local ServiceAccount.
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles"]
    verbs: ["bind"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: $prefix-installer
subjects:
  - kind: ServiceAccount
    name: $service_account
    namespace: $runtime_namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: $prefix-installer
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: $prefix-installer-clusterrole-scope
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: ["rbac.authorization.k8s.io"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE", "DELETE"]
        resources: ["clusterroles"]
  validations:
    - expression: >-
        request.userInfo.username != "$installer_principal" ||
        (request.operation == "DELETE" ?
          (oldObject.metadata.name.matches('^ep-runner-[a-z0-9-]+-envplane-runner-feature-env-namespace-reader$') &&
           oldObject.metadata.labels['app.kubernetes.io/managed-by'] == "Helm" &&
           oldObject.metadata.labels['app.kubernetes.io/name'] == "envplane-runner" &&
           oldObject.metadata.annotations['meta.helm.sh/release-name'] == oldObject.metadata.labels['app.kubernetes.io/instance'] &&
           oldObject.metadata.annotations['meta.helm.sh/release-namespace'] == "$runtime_namespace")
          :
          (object.metadata.name.matches('^ep-runner-[a-z0-9-]+-envplane-runner-feature-env-namespace-reader$') &&
           object.metadata.labels['app.kubernetes.io/managed-by'] == "Helm" &&
           object.metadata.labels['app.kubernetes.io/name'] == "envplane-runner" &&
           object.metadata.annotations['meta.helm.sh/release-name'] == object.metadata.labels['app.kubernetes.io/instance'] &&
           object.metadata.annotations['meta.helm.sh/release-namespace'] == "$runtime_namespace" &&
           object.rules.size() == 1 &&
           object.rules[0].apiGroups == [""] &&
           object.rules[0].resources == ["namespaces"] &&
           object.rules[0].verbs.size() >= 1 &&
           object.rules[0].verbs.all(verb, verb == "get" || verb == "delete") &&
           object.rules[0].verbs.exists(verb, verb == "get") &&
           object.rules[0].resourceNames.size() >= 1 &&
           object.rules[0].resourceNames.all(name, name.matches('^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'))))
      message: "remote installer may manage only bounded Helm-owned Runner namespace-reader ClusterRoles"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: $prefix-installer-clusterrole-scope
spec:
  policyName: $prefix-installer-clusterrole-scope
  validationActions: ["Deny"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: $prefix-installer-clusterrolebinding-scope
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: ["rbac.authorization.k8s.io"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE", "DELETE"]
        resources: ["clusterrolebindings"]
  validations:
    - expression: >-
        request.userInfo.username != "$installer_principal" ||
        (request.operation == "DELETE"
          ? ((["$capability_role", "$inventory_role", "$metadata_role"].exists(name, name == oldObject.roleRef.name)) ||
              (oldObject.metadata.name.matches('^ep-agent-[a-z0-9-]+-envplane-agent-cluster-capability-reader$') &&
               oldObject.roleRef.name == oldObject.metadata.name &&
               oldObject.subjects.exists(subject, subject.kind == "ServiceAccount" && subject.namespace == "$runtime_namespace")) ||
              (oldObject.metadata.name.matches('^ep-runner-[a-z0-9-]+-envplane-runner-feature-env-namespace-reader$') &&
               oldObject.roleRef.name == oldObject.metadata.name &&
               oldObject.subjects.size() == 1 &&
               oldObject.subjects[0].kind == "ServiceAccount" &&
               oldObject.subjects[0].namespace == "$runtime_namespace")) &&
            oldObject.metadata.labels['app.kubernetes.io/managed-by'] == "Helm" &&
            ((oldObject.metadata.labels['app.kubernetes.io/component'] == "cluster-agent" &&
              oldObject.metadata.labels['app.kubernetes.io/name'] == "envplane-agent") ||
             oldObject.metadata.labels['app.kubernetes.io/name'] == "envplane-runner")
          : (["$capability_role", "$inventory_role", "$metadata_role"].exists(name, name == object.roleRef.name) ||
             (object.metadata.name.matches('^ep-runner-[a-z0-9-]+-envplane-runner-feature-env-namespace-reader$') &&
              object.roleRef.name == object.metadata.name &&
              object.subjects.size() == 1 &&
              object.subjects[0].kind == "ServiceAccount" &&
              object.subjects[0].namespace == "$runtime_namespace" &&
              object.metadata.labels['app.kubernetes.io/name'] == "envplane-runner")) &&
            object.metadata.labels['app.kubernetes.io/managed-by'] == "Helm" &&
            ((object.metadata.labels['app.kubernetes.io/component'] == "cluster-agent") ||
             object.metadata.labels['app.kubernetes.io/name'] == "envplane-runner"))
      message: "remote installer may bind only fixed capability roles or bounded Helm-owned Runner namespace readers"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: $prefix-installer-clusterrolebinding-scope
spec:
  policyName: $prefix-installer-clusterrolebinding-scope
  validationActions: ["Deny"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: $prefix-cluster-capability-reader
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingressclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: $prefix-namespace-inventory-reader
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: $prefix-namespace-metadata-reader
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    resourceNames:
EOF
for namespace in "${all_namespaces[@]}"; do
  printf '      - %s\n' "$namespace"
done
cat <<EOF
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: $prefix-rbac-manager
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: $prefix-discovery-parent
rules:
  - apiGroups: [""]
    resources: ["services", "configmaps", "resourcequotas", "limitranges", "persistentvolumeclaims", "serviceaccounts", "pods", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: $prefix-feature-env-writer-parent
rules:
  - apiGroups: [""]
    resources: ["configmaps", "events", "services", "resourcequotas", "limitranges", "persistentvolumeclaims", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "replicasets", "daemonsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
EOF

cat <<EOF
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: $prefix-runtime-manager
  namespace: $runtime_namespace
rules:
  - apiGroups: [""]
    resources: ["configmaps", "events", "persistentvolumeclaims", "pods", "secrets", "serviceaccounts", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: $prefix-runtime-manager
  namespace: $runtime_namespace
subjects:
  - kind: ServiceAccount
    name: $service_account
    namespace: $runtime_namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: $prefix-runtime-manager
EOF

for namespace in "${managed_namespaces[@]}"; do
  [[ "$namespace" == "$runtime_namespace" ]] && continue
  cat <<EOF
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: $prefix-discovery-reader
  namespace: $namespace
rules:
  - apiGroups: [""]
    resources: ["configmaps", "events", "persistentvolumeclaims", "serviceaccounts", "services", "pods", "resourcequotas", "limitranges"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: $prefix-discovery-reader
  namespace: $namespace
subjects:
  - kind: ServiceAccount
    name: $service_account
    namespace: $runtime_namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: $prefix-discovery-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: $prefix-discovery-parent
  namespace: $namespace
subjects:
  - kind: ServiceAccount
    name: $service_account
    namespace: $runtime_namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: $prefix-discovery-parent
EOF
done

for namespace in "${validated_flux_namespaces[@]}"; do
  cat <<EOF
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: $prefix-flux-reader
  namespace: $namespace
rules:
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: ["kustomizations"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: ["helmreleases"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: ["gitrepositories", "helmrepositories", "ocirepositories", "buckets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: $prefix-flux-reader
  namespace: $namespace
subjects:
  - kind: ServiceAccount
    name: $service_account
    namespace: $runtime_namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: $prefix-flux-reader
EOF
done
