#!/usr/bin/env bash
# Render the target-cluster RBAC profile consumed by envplane's Remote Cluster
# Reconciler. The result contains no credentials and can be reviewed before it
# is applied. Dynamic project namespaces receive workload access only through
# server-owned RoleBindings after ownership verification.
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: render-remote-cluster-rbac-profile.sh --cluster-id ID [options]

Options:
  --runtime-namespace NAME   Namespace for the envplane target runtimes (default: envplane-system)
  --service-account NAME     ServiceAccount used by the target kubeconfig (default: envplane-remote-cluster-ID)
  --managed-namespace NAME   Existing namespace for read-only workload discovery; repeatable
  --flux-namespace NAME      Existing namespace that also permits read-only Flux status; repeatable
  --help                     Show this help
EOF
}

cluster_id=""
runtime_namespace="envplane-system"
service_account=""
managed_namespaces=()
flux_namespaces=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --cluster-id) cluster_id="${2:-}"; shift 2 ;;
    --runtime-namespace) runtime_namespace="${2:-}"; shift 2 ;;
    --service-account) service_account="${2:-}"; shift 2 ;;
    --managed-namespace) managed_namespaces+=("${2:-}"); shift 2 ;;
    --flux-namespace) flux_namespaces+=("${2:-}"); shift 2 ;;
    --help) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

dns_label='^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
for value in "$cluster_id" "$runtime_namespace"; do
  if [[ ! "$value" =~ $dns_label ]] || [[ ${#value} -gt 63 ]]; then
    echo "cluster ID and namespace names must be Kubernetes DNS labels up to 63 characters" >&2
    exit 2
  fi
done
if [[ -z "$service_account" ]]; then
  service_account="envplane-remote-cluster-$cluster_id"
fi
if [[ ! "$service_account" =~ $dns_label ]] || [[ ${#service_account} -gt 63 ]]; then
  echo "service account name must be a Kubernetes DNS label up to 63 characters" >&2
  exit 2
fi
for namespace in "${flux_namespaces[@]}"; do
  if [[ ! "$namespace" =~ $dns_label ]] || [[ ${#namespace} -gt 63 ]]; then
    echo "Flux namespace names must be Kubernetes DNS labels up to 63 characters" >&2
    exit 2
  fi
done

prefix="envplane-remote-cluster-$cluster_id"
installer_principal="system:serviceaccount:$runtime_namespace:$service_account"
capability_role="$prefix-cluster-capability-reader"
inventory_role="$prefix-namespace-inventory-reader"
metadata_role="$prefix-namespace-metadata-reader"
all_namespaces=("$runtime_namespace")
for namespace in "${managed_namespaces[@]}"; do
  if [[ ! "$namespace" =~ $dns_label ]] || [[ ${#namespace} -gt 63 ]]; then
    echo "managed namespace names must be Kubernetes DNS labels up to 63 characters" >&2
    exit 2
  fi
  if [[ " $'\n'${all_namespaces[*]}$'\n' " != *$'\n'"$namespace"$'\n'* ]]; then
    all_namespaces+=("$namespace")
  fi
done

cat <<EOF
# Generated by scripts/render-remote-cluster-rbac-profile.sh.
# Review this file before applying it. It intentionally contains no token,
# kubeconfig or other credential material.
apiVersion: v1
kind: Namespace
metadata:
  name: $runtime_namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: $service_account
  namespace: $runtime_namespace
  labels:
    app.kubernetes.io/part-of: envplane
    envplane.io/remote-cluster-id: $cluster_id
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: $prefix-installer
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "create", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles"]
    resourceNames:
      - $prefix-cluster-capability-reader
      - $prefix-namespace-inventory-reader
      - $prefix-namespace-metadata-reader
      - $prefix-rbac-manager
      - $prefix-discovery-parent
      - $prefix-feature-env-writer-parent
    verbs: ["bind"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles"]
    resourceNames:
      - $prefix-namespace-metadata-reader
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: $prefix-installer
subjects:
  - kind: ServiceAccount
    name: $service_account
    namespace: $runtime_namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: $prefix-installer
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: $prefix-installer-clusterrolebinding-scope
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: ["rbac.authorization.k8s.io"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE", "DELETE"]
        resources: ["clusterrolebindings"]
  validations:
    - expression: >-
        request.userInfo.username != "$installer_principal" ||
        (request.operation == "DELETE"
          ? ["$capability_role", "$inventory_role", "$metadata_role"].exists(name, name == oldObject.roleRef.name) &&
            oldObject.metadata.labels['app.kubernetes.io/managed-by'] == "Helm" &&
            oldObject.metadata.labels['app.kubernetes.io/component'] == "cluster-agent"
          : ["$capability_role", "$inventory_role", "$metadata_role"].exists(name, name == object.roleRef.name) &&
            object.metadata.labels['app.kubernetes.io/managed-by'] == "Helm" &&
            object.metadata.labels['app.kubernetes.io/component'] == "cluster-agent")
      message: "remote installer may bind or remove only its read-only capability roles"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: $prefix-installer-clusterrolebinding-scope
spec:
  policyName: $prefix-installer-clusterrolebinding-scope
  validationActions: ["Deny"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: $prefix-cluster-capability-reader
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingressclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: $prefix-namespace-inventory-reader
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: $prefix-namespace-metadata-reader
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    resourceNames:
EOF
for namespace in "${all_namespaces[@]}"; do
  printf '      - %s\n' "$namespace"
done
cat <<EOF
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: $prefix-rbac-manager
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: $prefix-discovery-parent
rules:
  - apiGroups: [""]
    resources: ["services", "configmaps", "resourcequotas", "limitranges", "persistentvolumeclaims", "serviceaccounts", "pods", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: $prefix-feature-env-writer-parent
rules:
  - apiGroups: [""]
    resources: ["configmaps", "events", "services", "resourcequotas", "limitranges", "persistentvolumeclaims", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "replicasets", "daemonsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
EOF

cat <<EOF
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: $prefix-runtime-manager
  namespace: $runtime_namespace
rules:
  - apiGroups: [""]
    resources: ["configmaps", "events", "persistentvolumeclaims", "pods", "secrets", "serviceaccounts", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: $prefix-runtime-manager
  namespace: $runtime_namespace
subjects:
  - kind: ServiceAccount
    name: $service_account
    namespace: $runtime_namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: $prefix-runtime-manager
EOF

for namespace in "${managed_namespaces[@]}"; do
  [[ "$namespace" == "$runtime_namespace" ]] && continue
  cat <<EOF
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: $prefix-discovery-reader
  namespace: $namespace
rules:
  - apiGroups: [""]
    resources: ["configmaps", "events", "persistentvolumeclaims", "serviceaccounts", "services", "pods", "resourcequotas", "limitranges"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: $prefix-discovery-reader
  namespace: $namespace
subjects:
  - kind: ServiceAccount
    name: $service_account
    namespace: $runtime_namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: $prefix-discovery-reader
EOF
done

for namespace in "${flux_namespaces[@]}"; do
  cat <<EOF
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: $prefix-flux-reader
  namespace: $namespace
rules:
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: ["kustomizations"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: ["helmreleases"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: ["gitrepositories", "helmrepositories", "ocirepositories", "buckets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: $prefix-flux-reader
  namespace: $namespace
subjects:
  - kind: ServiceAccount
    name: $service_account
    namespace: $runtime_namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: $prefix-flux-reader
EOF
done
