{{- if and .Values.image.createPullSecret .Values.registry.token -}}
{{- $auth := printf "%s:%s" .Values.registry.username .Values.registry.token | b64enc -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.pullSecretName | quote }}
  labels:
    {{- include "envpilot-init.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ dict "auths" (dict .Values.registry.server (dict "username" .Values.registry.username "password" .Values.registry.token "auth" $auth)) | toJson | b64enc | quote }}
{{- end }}
