{{- if and (not .Values.registry.existingTokenSecret) .Values.registry.token -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "envpilot-init.fullname" . }}-registry-token
  labels:
    {{- include "envpilot-init.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.registry.token | quote }}
{{- end }}
