{{- if and .Values.installer.createNamespace (not (lookup "v1" "Namespace" "" .Values.installer.namespace)) -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.installer.namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "envpilot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: envpilot
{{- end }}
