{{- if .Values.registry.createPullSecret -}}
{{- $auth := printf "%s:%s" .Values.registry.username .Values.registry.password | b64enc -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registry.pullSecretName | quote }}
  labels:
    app.kubernetes.io/name: envpilot
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ dict "auths" (dict .Values.registry.server (dict "username" .Values.registry.username "password" .Values.registry.password "email" .Values.registry.email "auth" $auth)) | toJson | b64enc | quote }}
{{- end }}
