{{- if and (not .Values.registry.existingTokenSecret) .Values.registry.token -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "envpilot.fullname" . }}-registry-token
  namespace: {{ .Values.installer.namespace | quote }}
  labels:
    {{- include "envpilot.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.registry.token | quote }}
{{- end }}
